language: python

python:
  - 3.5
  - 3.6
  - "3.7-dev"

install:
  - pip install -r requirements.txt -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "TaJrfBS/HXFQpruOmXkXI0RJA7D//OJ4r1TAo3QHk1A3VUdYglufPsju9h6YwtqH8MA3OvCn4Z0Gjovi8bHFKBsbt4IwhMA5SgXP/C+DfdRlWhbitMpsIG1Q0cxyoVmoZeEB9sU4iNRm0K2A8WaZy2n4fPFI6eiIc4/6GpQey6b8Vs6fBRQ2jOGLRkTtP6f5q4NMuy9hD8bDqr5cqIkZh2MqQFzbXdv8pDDApNo81s9G1cCkcuJxHOM6ch7dYeefb4Py/r5hFdzg4xpeME93ZpDL0bP8C0cVZHbePETYw+sSZrupFxFHzZtq6v17lIr9dtR3KPfRHO5XOcwtrGh/n7OXwa+GKkvnhmRYwoqxx8yddkVVdY1NldNpeqt/+yD0XQYKpmmKH8aZLYhQRptA5sd5KL15ryArYq9AT9DFQcehBanvZTFYq+95gHAXoGPTy/f7lXKBYLPRWasPXQsxZ+KSlEdb+5+TPsBkMVjiwl+wnFM3mgKdL2VyvRnna9vZ7kdArmiqzdAk0DHZiz68RHaQSPh0zSxQvYKRlybtLlzz/MKXwCdH+2TQAi3Qu6A3L3LQUWpZFmabP3nAI6dUsrwbsN4FMY/hfbAMfFjjrLNvCvww7Qvu14F6Ltbi6YKt7784szhuBg3+9GxBSgnH2gJM+BOUcNIiL2eQDDiJgI0="

script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
